# 应用名称
spring:
  application:
    name: zull
  cloud:
    config:
      override-none: true
server:
  port: 3001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
zuul:
  routes:
    sp2-itemservice: /item-service/**
    sp3-userservice: /user-service/**
    sp4-orderservice: /order-service/**

  retryable: true
#ribbon:
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
