# 应用名称
spring:
  application:
    name: zuul
  cloud:
    config:
      override-none: true
  rabbitmq:
   host: localhost
   port: 5672
   username: admin
   password: admin
server:
  port: 3001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

  retryable: true
#ribbon:
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
